server:
  port: 8093

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: DEBUG


spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: dashboard
            client-secret: 7bd32f17-43aa-4af3-83bd-f04d4dca2c34
            clientName: dashboard
            authorization-grant-type: authorization_code
            redirectUriTemplate: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            authorization-uri: http://localhost:8080/auth/realms/blueport/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/blueport/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/blueport/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8080/auth/realms/blueport/protocol/openid-connect/certs
            user-name-attribute: preferred_username
